/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardSetupRouteImport } from './routes/_dashboard/setup'
import { Route as DashboardIntegrationsRouteImport } from './routes/_dashboard/integrations'
import { Route as DashboardBugsRouteImport } from './routes/_dashboard/bugs'
import { Route as DashboardAccessRouteImport } from './routes/_dashboard/access'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBugsRoute = DashboardBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccessRoute = DashboardAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/access': typeof DashboardAccessRoute
  '/bugs': typeof DashboardBugsRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/setup': typeof DashboardSetupRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/access': typeof DashboardAccessRoute
  '/bugs': typeof DashboardBugsRoute
  '/integrations': typeof DashboardIntegrationsRoute
  '/setup': typeof DashboardSetupRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_dashboard/access': typeof DashboardAccessRoute
  '/_dashboard/bugs': typeof DashboardBugsRoute
  '/_dashboard/integrations': typeof DashboardIntegrationsRoute
  '/_dashboard/setup': typeof DashboardSetupRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/access'
    | '/bugs'
    | '/integrations'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/access'
    | '/bugs'
    | '/integrations'
    | '/setup'
    | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/_dashboard/access'
    | '/_dashboard/bugs'
    | '/_dashboard/integrations'
    | '/_dashboard/setup'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/setup': {
      id: '/_dashboard/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/integrations': {
      id: '/_dashboard/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/bugs': {
      id: '/_dashboard/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof DashboardBugsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/access': {
      id: '/_dashboard/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof DashboardAccessRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAccessRoute: typeof DashboardAccessRoute
  DashboardBugsRoute: typeof DashboardBugsRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccessRoute: DashboardAccessRoute,
  DashboardBugsRoute: DashboardBugsRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
